version: 0.0
os: linux

files:
  - source: build/
    destination: /var/www/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/restart-apache.sh
      timeout: 180
      runas: root
