version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
