version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Instalando dependências..."
      - npm install
      # se quiser deixar mais determinístico:
      # - npm ci
  build:
    commands:
      - echo "Gerando build de produção..."
      - npm run build

artifacts:
  files:
    - '**/*'        # Envia tudo (appspec.yml, scripts/, build/, etc.)
  discard-paths: no
