version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - npm install

  build:
    commands:
      - echo "Gerando build da aplicação..."
      - npm run build

artifacts:
  files:
    - '**/*'        # Envia TUDO para o CodeDeploy (inclui appspec.yml e scripts/)
  discard-paths: no
